{
 "title": "Backend Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasa de Peticiones (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Tasa de Errores (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"[45].*\"}[1m])) / sum(rate(http_requests_total[1m])) * 100",
     "legendFormat": "% Errores"
    }
   ]
  },
  {
   "title": "Latencia (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "Uso de Memoria (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Allocated Memory (Bytes)" }
   ]
  },
  {
   "title": "Goroutines Activas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Goroutines" }
   ]
  }
 ]
}