server {
	    listen 80;
	        server_name localhost;

		    # --- TUS CONFIGURACIONES ---
		    # Aumentar límite para subir fotos de facturas grandes
		    client_max_body_size 10M;

		        # 1. Frontend (React)
		        location / {
				        root   /usr/share/nginx/html;
					        index  index.html;
						        try_files $uri $uri/ /index.html;
							    }

							        # 2. Backend API
							        location /api {
									        # Conecta con el contenedor 'backend' en el puerto 8080
									        proxy_pass http://backend:8080; 
										        
										        proxy_set_header Host $host;
											        proxy_set_header X-Real-IP $remote_addr;
												        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
													        proxy_set_header X-Forwarded-Proto $scheme;

														        # Timeouts para subidas lentas
														        proxy_read_timeout 300s;
															        proxy_connect_timeout 75s;
																    }

																        # 3. Archivos Estáticos (Uploads)
																        location /uploads {
																		        proxy_pass http://backend:8080;
																			        proxy_set_header Host $host;
																				    }

		# 4. WebSockets
		location /ws {
			proxy_pass http://backend:8080/ws;
			
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			
			proxy_set_header Host $host;
			proxy_read_timeout 86400; 
		}

		# 5. Grafana
		location /grafana/ {
			proxy_pass http://grafana:3000;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}
